### PR TITLE
Support Python 2.7, 3.4, 3.5, 3.6

### PR DESCRIPTION
**Pull request by mruffalo**
Not many changes were required:

* Relative imports
* Using the `six` package for a few renamed modules/builtin functions/etc.
* Using the `__future__.print_function` import in `test_concat_gctoo.py`

All tests passed under 2.7, 3.4, 3.5, and 3.6, as per an older Travis CI build at https://travis-ci.org/mruffalo/cmapPy/builds/294957365 -- though that build is from an older version of these changes which also included testing Python 3.3. I'm sure everything will work under Python 3.3 also, but the `h5py` package fails to install under 3.3 on the Travis CI service, so that version probably shouldn't be marked as "supported" without any test coverage.

### CODE REVIEW

**Comment by levlitichev** [comment]
Thanks for the PR, @mruffalo. The changes look great. It looks like you've fixed our relative imports to be compatible with py3, but we've been meaning to switch all relative imports to absolute imports. I'll take a stab at adding this change to the PR

**Comment by levlitichev** [comment]
Sorry for accidentally closing! Thanks for the PR, @mruffalo. There are a few things we want to review first, but from a glance, the changes look great.

**Comment by oena** [comment]
Thanks for taking the time to do this, @mruffalo! Appreciate it.

**Comment by mruffalo** [comment]
My pleasure! This was much less work than a similar pull request I made in the old l1ktools repository: https://github.com/cmap/l1ktools/pull/14 -- especially since this code was written using modern Python 2.x idioms/style, which really eases the process of making it run under 3.x also. It was also very useful to already have Travis CI testing in place.

**Comment by oena** [comment]
@mruffalo that was the whole idea behind refactoring it, so I'm very happy to hear it's not just us who find it easier to work with!

**Pull request merged**
